In [1]:
import tensorflow as tf 
from tensorflow import keras 
import pandas as pd
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [4]:
link = r'loc'
shit = pd.read_csv(link, delimiter=';')
op = shit['feeling'].unique()
print(op)
li = []
for o in op:
    p = shit.loc[shit['feeling'] == o]
    li.append(p)

for c,x in enumerate(li):
    onehot = [one_hot(word, 16185) for word in np.array(x['statement'])]
    li[c] = onehot

Lab = shit['feeling']
Lab = [one_hot(word, 6) for word in np.array(Lab)]
data = np.concatenate((li[0][:500],li[1][:500],li[2][:500],li[3][:500],li[4][:500],li[5][:500]), axis=0)
Data = []
for c in range(500):
    for x in range(6):
        Data.append(data[x*500 + c])

test = np.concatenate((np.full((500), 0), np.full((500), 1), np.full((500), 2), np.full((500), 3), np.full((500), 4), np.full((500), 5)))
data.shape
yData = []
for c in range(500):
    for x in range(6):
        arr = list(np.zeros(6))
        arr[x] = 1
        yData.append(arr)


['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']


<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray


In [5]:
trainData = keras.preprocessing.sequence.pad_sequences(Data, maxlen = 64)
lab = []
for val in Lab:
    arr = np.zeros(6)
    arr[val] = 1
    lab.append(arr)
lab = np.array(lab)
lab = lab.reshape(16000,6)
yData = np.array(yData)
print(trainData.shape, yData, lab)


(3000, 64) [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]] [[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [2]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(16185, 128),
    tf.keras.layers.LSTM(units = 128, activation="relu", return_sequences=True),
    tf.keras.layers.LSTM(units = 64, activation="relu", return_sequences=True),
    tf.keras.layers.LSTM(units = 32, activation="relu", return_sequences=False),
    tf.keras.layers.Dense(6, activation="softmax")
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 128)         2071680   
                                                                 
 lstm (LSTM)                 (None, None, 128)         131584    
                                                                 
 lstm_1 (LSTM)               (None, None, 64)          49408     
                                                                 
 lstm_2 (LSTM)               (None, 32)                12416     
                                                                 
 dense (Dense)               (None, 6)                 198       
                                                                 
Total params: 2,265,286
Trainable params: 2,265,286
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(loss='categorical_crossentropy', optimizer="adam" , metrics=['accuracy'])
model.fit(trainData, yData, epochs=3, steps_per_epoch=2000, validation_split=0.2,shuffle=False)

Epoch 1/3
2000/2000 [==============================] - 114s 56ms/step - loss: 6.0964 - accuracy: 0.6660 - val_loss: 1.2880 - val_accuracy: 0.5717
Epoch 2/3
2000/2000 [==============================] - 91s 45ms/step - loss: 1.8338 - accuracy: 0.7559 - val_loss: 1.3302 - val_accuracy: 0.6817


['sadness' 'anger' 'love' 'surprise' 'fear' 'joy']

In [9]:
32896 *4


131584

In [12]:
statement = "i am loving you"
statement = [np.array(one_hot(statement, 16185), dtype="int32")]
statement = keras.preprocessing.sequence.pad_sequences(statement, maxlen = 64)
print(statement)
print(model.predict(statement.reshape(-1, 64)))

[[    0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
  14924  1992 15109  4893]]
[[4.3352108e-07 4.0583518e-07 9.9972516e-01 9.7155669e-07 2.4132106e-08
  2.7287923e-04]]


In [13]:
model.save("SmileInPain_loss=crossent.h5")

Remember that the bias is a parameter that is always add as a parameter in the previous layer

In [3]:
dir(tf.keras.layers)

['AbstractRNNCell',
 'Activation',
 'ActivityRegularization',
 'Add',
 'AdditiveAttention',
 'AlphaDropout',
 'Attention',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D',
 'AveragePooling3D',
 'AvgPool1D',
 'AvgPool2D',
 'AvgPool3D',
 'BatchNormalization',
 'Bidirectional',
 'CategoryEncoding',
 'CenterCrop',
 'Concatenate',
 'Conv1D',
 'Conv1DTranspose',
 'Conv2D',
 'Conv2DTranspose',
 'Conv3D',
 'Conv3DTranspose',
 'ConvLSTM1D',
 'ConvLSTM2D',
 'ConvLSTM3D',
 'Convolution1D',
 'Convolution1DTranspose',
 'Convolution2D',
 'Convolution2DTranspose',
 'Convolution3D',
 'Convolution3DTranspose',
 'Cropping1D',
 'Cropping2D',
 'Cropping3D',
 'Dense',
 'DenseFeatures',
 'DepthwiseConv2D',
 'Discretization',
 'Dot',
 'Dropout',
 'ELU',
 'Embedding',
 'Flatten',
 'GRU',
 'GRUCell',
 'GaussianDropout',
 'GaussianNoise',
 'GlobalAveragePooling1D',
 'GlobalAveragePooling2D',
 'GlobalAveragePooling3D',
 'GlobalAvgPool1D',
 'GlobalAvgPool2D',
 'GlobalAvgPool3D',
 'GlobalMaxPool1D',
 'GlobalM